- name: Sync the hardware clock from the system clock
  listen: time_config_changed
  command: hwclock --systohc

- name: Restart crond
  listen: time_config_changed
  service:
    name: cron
    state: restarted

- name: Register new aliases
  listen: aliases_changed
  command: newaliases

- name: Restart Postfix
  listen: postfix_config_changed
  service:
    name: postfix
    state: restarted
