apt_cache_valid_time: 3600

regexp:
  fs_path: '^(?:/[\w\-\.\*]*)+$'
  timezone: '^[\w\-]+(?:[\+\-]\d+)?(?:/[\w\-]+)?$'
  locale: '^[a-z]{2}_[A-Z]{2}(?:\.[A-Z\d\-]+)?$'
  username: '^[a-z][a-z\d\-]{,15}$'
  hostname: '^(?:[A-Za-z\d]+(?:[\-\.][A-Za-z\d]+)*|\d{1,3}(\.\d{1.3}){3})$'
  email_address: '^[\w\+\-~]+(?:\.[\w\+\-~]+)*@[A-Za-z\d]+(?:[\-\.][A-Za-z\d]+)*$'
  ssh_key: '^[a-z\d]+(?:-[a-z\d]+)* AAAA[A-Za-z\d\+/]+=*(?: .+)?'
